CREATE TABLE GAMES (
    ID          INTEGER PRIMARY KEY,
    MAP         VARCHAR(64) NOT NULL,
    OUTCOME     VARCHAR(4) NOT NULL,
    END_REASON  VARCHAR(24) NOT NULL,
    DURATION    INT NOT NULL,
    GAME_MODE   VARCHAR(24) NOT NULL,
    PLAYERS     VARCHAR(255) NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE RELICS (
    ID          SERIAL PRIMARY KEY,
    GAME_ID     INTEGER,
    NAME        VARCHAR NOT NULL,
    WINNER      VARCHAR(50) NOT NULL,
    SCORE       INTEGER NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (GAME_ID) REFERENCES GAMES(ID)
);
